language: ruby
services:
  - docker
env:
  - CLOUDSDK_CORE_PROJECT=elated-oxide-340704
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
before_install:
  - openssl aes-256-cbc -K $encrypted_770126adc205_key -iv $encrypted_770126adc205_iv -in gcp-ci-secret.json.enc -out gcp-ci-secret.json -d
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin $DOCKER_REGISTRY
  - docker info
script:
  - echo "build docker image..."
  - docker build --platform linux/amd64 -t $TRAVIS_COMMIT-$TRAVIS_BUILD_ID .
  - docker tag $TRAVIS_COMMIT-$TRAVIS_BUILD_ID $DOCKER_REGISTRY/$DOCKER_REPO_URI:$TRAVIS_COMMIT
  - docker push $DOCKER_REGISTRY/$DOCKER_REPO_URI:$TRAVIS_COMMIT
  - echo "run grype container scan"...
  - curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b .
  - "./grype $DOCKER_REGISTRY/$DOCKER_REPO_URI:$TRAVIS_COMMIT --only-fixed --fail-on low"
  - echo "install gcloud cli and auth..."
  - gcloud version || true
  - gcloud auth login --cred-file=gcp-ci-secret.json.enc
  - gcloud config set account travis-k8s@${CLOUDSDK_CORE_PROJECT}.iam.gserviceaccount.com
  - gcloud config set core/account travis-k8s@${CLOUDSDK_CORE_PROJECT}.iam.gserviceaccount.com
  - gcloud config set compute/region us-central1-a
  - gcloud config set disable_prompts true
  - gcloud container clusters get-credentials nginx-1-cluster --region us-central1-a
  - echo "run a kubectl command"
  - kubectl get pods -A

# project : elated-oxide-340704
# account : travis-k8s@elated-oxide-340704.iam.gserviceaccount.com
# kubectl create deployment hello-server \
#    --image=us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0