language: ruby
services:
  - docker
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
before_install:
  - openssl aes-256-cbc -K $encrypted_770126adc205_key -iv $encrypted_770126adc205_iv -in gcp-ci-secret.json.enc -out gcp-ci-secret.json -d
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin $DOCKER_REGISTRY
  - docker info
script:
  - echo "build docker image..."
  - docker build --platform linux/amd64 -t $TRAVIS_COMMIT-$TRAVIS_BUILD_ID .
  - docker tag $TRAVIS_COMMIT-$TRAVIS_BUILD_ID $DOCKER_REGISTRY/$DOCKER_REPO_URI:$TRAVIS_COMMIT
  - docker push $DOCKER_REGISTRY/$DOCKER_REPO_URI:$TRAVIS_COMMIT
  - echo "run grype container scan"...
  - curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh
    -s -- -b .
  - "./grype $DOCKER_REGISTRY/$DOCKER_REPO_URI:$TRAVIS_COMMIT --only-fixed --fail-on low"
  - echo "install gcloud cli..."
  - gcloud version || true
