apiVersion: v1
kind: Service
metadata:
  name: ltc
  labels:
    app: ltc
spec:
  ports:
    - port: 9333
      name: ltc
  clusterIP: None
  selector:
    app: ltc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ltc
spec:
  selector:
    matchLabels:
      app: ltc
  serviceName: "litecoind"
  replicas: 1
  template:
    metadata:
      labels:
        app: ltc
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: ltc
          image: registry.gitlab.com/rojomisin/ltc-devops/litecoind:9
          ports:
            - containerPort: 9333
              name: ltc
          volumeMounts:
            - name: blocks
              mountPath: /var/app-data
      volumes:
        - name: blocks
          # This GCE PD must already exist.
          gcePersistentDisk:
            pdName: ltc-data
            fsType: ext4
