apiVersion: v1
kind: Service
metadata:
  name: ltc
  labels:
    app: ltc
spec:
  ports:
    - port: 9332
      name: ltc
  clusterIP: None
  selector:
    app: ltc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ltc
spec:
  selector:
    matchLabels:
      app: ltc # Label selector that determines which Pods belong to the StatefulSet
      # Must match spec: template: metadata: labels
  serviceName: "litecoind"
  replicas: 1
  template:
    metadata:
      labels:
        app: ltc # Pod template's label selector
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: ltc
          image: registry.gitlab.com/rojomisin/ltc-devops
          ports:
            - containerPort: 9332
              name: ltc
          volumeMounts:
            - name: blocks
              mountPath: /home/litecoin/.litecoin
  volumeClaimTemplates:
    - metadata:
        name: blocks
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
